### ISSUE TITLE
Slate is broken in PyPI

### ISSUE THREAD

**Issue by ranisalt** [timClicks/slate#16]
Something in pdfminer has changed and `PDFDocument` class is not in `pdfminer.pdfparser` anymore, it's now in `pdfminer.pdfdocument`. I figured out you have fixed this problem here in GitHub, but the version in PyPI still has this problem. Could you please reupload it?

**Comment by filwaitman** [comment]
:+1:

Same problem here.  =/
Reuploading on Pypi must solve this.

**Comment by SimKennedy** [comment]
+1
I've got the unenviable task of automating conversion of many microsoft documents (pdf, doc, xls, etc.) to txt format. The PDF miner usage is so messy that I really appreciate your work here.
I'd like to automate the install with pip for simplicity though so would really appreciate a PyPi update :)

**Comment by jasco** [comment]
I had the same problem.  pip install from pypi installs 0.3.  In the meantime I was able to install 0.4.1 directly from github `pip install git+https://github.com/timClicks/slate`

**Comment by schamp** [comment]
Thanks for those instructions, @jasco, that was just what I needed.

**Comment by timClicks** [comment]
Sorry for letting this slide (2015 has been a difficult year). I'll need to check that PyPI can understand the python 2 vs python 3 dependency change, but there should be a new PyPI version up pretty soon!

**Comment by timClicks** [comment]
[New version up on PyPI](https://pypi.python.org/pypi/slate) :checkered_flag:

**Comment by ranisalt** [comment]
Oh yeah! Sweet, thanks Tim.
