### ISSUE TITLE
Error parsing a pdf with cStringIO support

### ISSUE THREAD

**Issue by jasco** [timClicks/slate#21]
Slate: master head: ff61328388845389325e2247f18f8fbe75457b3f
Ubuntu 14.04 x64
Python 2.7.6

Received the following error when cStringIO is available for import.

    .../lib/python2.7/site-packages/slate/slate.pyc in __init__(self, file, password, just_text, check_extractable)
         50                self.resmgr, self.device)
         51             for page in PDFPage.create_pages(self.doc):
    ---> 52                 self.append(self.interpreter.process_page(page))
         53             self.metadata = self.doc.info
         54         if just_text:

    .../lib/python2.7/site-packages/slate/slate.pyc in process_page(self, page)
         34             ctm = (1,0,0,1, -x0,-y0)
         35         self.device.outfp.seek(0)
    ---> 36         self.device.outfp.buf = ''
         37         self.device.begin_page(page, ctm)
         38         self.render_contents(page.resources, page.contents, ctm=ctm)

    AttributeError: 'cStringIO.StringO' object has no attribute 'buf'

Forcing the use of StringIO instead of cStringIO in slate.py fixed the problem.

**Comment by timClicks** [comment]
Thanks for looking into this Joel. Maybe we could just pass on
AttributeError? That way we wouldn't need the far slower module.

**Comment by jasco** [comment]
Thanks for the quick response.

If I understand your suggestion correctly, currently the error is indeed being passed on.  So, the client could catch it, but I don't see how the client code can recover from the exception.

I only looked at it long enough to try to figure a work around.  I'm guessing that buf is being cleared because the StringIO is being reused on subsequent pages?  I read that the preferred approach is to create a new StringIO object rather than trying to clear it.  I didn't look into TextConvert where it is being used, but maybe outfp could be given a new StringIO instance?

Also, I noticed in the documentation that cStringIO does not support unicode.  Without some study, I don't know if unicode text in a pdf document will require that outfp support unicode or not.  If it does and a work around is found for the buf not found in cStringIO error, maybe the choice of cStringIO vs StringIO could further be affected by a flag indicating whether unicode support is required.

**Comment by jasco** [comment]
I separately encountered a similar case where I wanted to clear StringIO and used `truncate`.  I tested the following change to slate.py and it resolved the problem I reported.

    36c36
    <         self.device.outfp.buf = ''
    ---
    >         self.device.outfp.truncate(0)

**Comment by timClicks** [comment]
That's a neat idea @jasco ... do you want to submit a PR and be acknowledged via the git history?

**Comment by jasco** [comment]
It appears that 43614f2716fb6020d31bfde64712636b084c417b removed the clearing of outfp altogether but the result is, as you might guess, commingling of text from different pages.  I'll add a test and the patch.

**Comment by timClicks** [comment]
Closing as the merge seems to have been a success. Thanks again @jasco
