### ISSUE TITLE
import error for slate.py file

### ISSUE THREAD

**Issue by KurtOstergaard** [timClicks/slate#25]
`from pdfminer.pdfparser import PDFParser, PDFDocument`

in slate.py generates an error 

However, this

`from pdfminer.pdfparser import PDFParser`    
`from pdfminer.pdfdocument import PDFDocument`

does not.

**Comment by GeorgeVentura** [comment]
Use `pip install git+https://github.com/timClicks/slate` to install, instead of `pip install slate` which installs the older version of slate which isn't update against the newest version of pdfminer

**Comment by pchaigno** [comment]
@timClicks Looks like `pip` only installs version 0.3 of slate. Could you push the last version to PyPI?

**Comment by a86c6f7964** [comment]
agreed pushing the latest to pypi would be great

**Comment by timClicks** [comment]
At long last, this should be fixed :checkered_flag:
