### ISSUE TITLE
Upload pypi package

### ISSUE THREAD

**Issue by ecarreras** [timClicks/slate#8]
Please publish the new version which fix the compatibility with pdfminer

**Comment by twolfson** [comment]
For anyone else curious, it looks like we need to use a `pdfminer` from before `20131113`. The latest one from then is `20110515`

```bash
pip install pdfminer==20110515
```

**Comment by timClicks** [comment]
Closing as #16 deals with PyPI and there shouldn't be any issues with inconsistent `pdfminer` versions anymore. Do reopen a ticket if you find anything new!
